[[mgr.prepend_keymap]]
on  = ["g", "d"]
run = 'cd "~/downloads/"'

[[mgr.prepend_keymap]]
on  = ["g", "m"]
run = 'cd "~/media/"'

[[mgr.prepend_keymap]]
on  = ["g", "p"]
run = 'cd "~/personal/"'

[[mgr.prepend_keymap]]
on  = ["g", "s"]
run = 'cd "~/school/"'

[[mgr.prepend_keymap]]
on  = ["g", "w"]
run = 'cd "~/work/"'

[[mgr.prepend_keymap]]
on  = ["g", "o"]
run = 'cd "~/media/pictures/"'

[[mgr.prepend_keymap]]
on  = ["g", "v"]
run = 'cd "~/media/videos/"'

[[mgr.prepend_keymap]]
on  = ["g", "n"]
run = 'cd "/mnt/nas"'

# drop to shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# copy to system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

# relative numbers
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

