[[mgr.prepend_keymap]]
on  = ["g", "d"]
run = 'cd "~/downloads/"'

[[mgr.prepend_keymap]]
on  = ["g", "m"]
run = 'cd "~/media/"'

[[mgr.prepend_keymap]]
on  = ["g", "p"]
run = 'cd "~/personal/"'

[[mgr.prepend_keymap]]
on  = ["g", "s"]
run = 'cd "~/school/"'

[[mgr.prepend_keymap]]
on  = ["g", "w"]
run = 'cd "~/work/"'

[[mgr.prepend_keymap]]
on  = ["g", "o"]
run = 'cd "~/media/pictures/"'

[[mgr.prepend_keymap]]
on  = ["g", "v"]
run = 'cd "~/media/videos/"'

[[mgr.prepend_keymap]]
on  = ["g", "n"]
run = 'cd "/mnt/nas"'

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"
